[package]
name = "typo-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
toml = "0.8.8"
too = { git = "https://github.com/museun/too", branch = "dev" }
crossterm = "0.27"
